return {
	-- {
	-- 	"sphamba/smear-cursor.nvim",
	-- 	opts = {},
	-- },
	-- {
	-- 	"nvzone/showkeys",
	-- 	cmd = "ShowkeysToggle",
	-- 	opts = {
	-- 		position = "top-center",
	-- 		maxkeys = 3,
	-- 		show_count = true,
	-- 		winopts = {
	-- 			focusable = false,
	-- 			relative = "editor",
	-- 			style = "minimal",
	-- 			border = "single",
	-- 			height = 1,
	-- 			row = 1,
	-- 			col = 0,
	-- 		},
	-- 	},
	-- },
	-- {
	-- 	"karb94/neoscroll.nvim",
	-- 	opts = {},
	-- },
}
